---
title: "Missing Data Analysis Homework 1"
author: "Tim Farkas"
date: "8/30/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Problem 5: Using simulation analysis

Load dependencies
```{r libraries}
library(tidyverse)
```

### Test Simulation

#### Create ground-truth and observed datasets
```{r full data set}
# parameters
n <- 10 # sample size
beta_x <- c(0, 0) # coefficients for relationship between x1 and x2 
beta_y <- c(3, 1, 2) # coef for rel btw X and Y
pmis <- 0.2 # proportion of missing data

# sample normal distribution to get full dataset
set.seed(1345)
X <- tibble(x1 = rnorm(n), 
            x2 = rnorm(n, beta_x[1] + beta_x[2] * x1))
y <-  rnorm(n, model.matrix(~ x1 + x2, data = X) %*% beta_y) 
full <- bind_cols(y = y, X)

# observed data with missing values
obs <- full %>%
  mutate_at(vars(y), function(y) ifelse(rbinom(n, 1, p = pmis), NA, y))
```

#### Imputation
```{r cc & mean & regression imputations}
# complete cases
obs_cc <- obs %>%
  drop_na()

# impute with mean
obs_mimp <- obs %>%
  replace_na(eval(.) %>% 
               summarize_all(mean, na.rm = TRUE))

# regression imputation
lm_mod <- lm(y ~ x1 + x2, data = obs_cc)
preds <- predict(lm_mod, newdata = obs)

obs_regimp <- obs %>%
  mutate_at(vars(y), function(y) ifelse(is.na(y), preds, y))

# get list of datasets 
obs_dfs <- list(cmplt_cases = obs_cc, 
                mean_imp = obs_mimp, 
                reg_imp = obs_regimp)
```

#### Evaluate Imputations
```{r}
# function to get stats for evaluation of bias, variance, MSE 
eval_stats <- function(df) {
               coefs <- lm(y ~ x1 + x2, data = df)$coefficients %>%
                 set_names(c("b0", "b1", "b2")) %>% 
                 bind_rows()
               mus <- df %>% summarize_all(mean)
               vars <- df %>% summarize_all(var)
               list(coefs = coefs, mus = mus, vars = vars)
}

eval_out <- map(obs_dfs, eval_stats)

```

## Monte Carlo Simulation

```{r}
# simulation function
eval_impute <- function(n, beta_x, beta_y, p_mis, seed = 1345) {
  
  require(dplyr)
  set.seed(seed)
  
  ### Create True and Observed Data
  # create ground-truth data
  X <- tibble(x1 = rnorm(n), 
              x2 = rnorm(n, beta_x[1] + beta_x[2] * x1))
  y <-  rnorm(n, mean = model.matrix(~ x1 + x2, data = X) %*% beta_y, 
              sd = 1) 
  full <- bind_cols(y = y, X)
  
  # create observed data with missing values
  obs <- full %>%
    mutate_at(vars(y), function(y) ifelse(rbinom(n, 1, p = p_mis), NA, y))
  
  ### Impute Data
  obs_cc <- obs %>%  # complete cases
    drop_na()
  
  obs_mimp <- obs %>%  # impute with mean
    replace_na(eval(.) %>% 
                 summarize_all(mean, na.rm = TRUE))
  
  # regression imputation
  lm_mod <- lm(y ~ x1 + x2, data = obs_cc)
  preds <- predict(lm_mod, newdata = obs)
  
  obs_regimp <- obs %>%
    mutate_at(vars(y), function(y) ifelse(is.na(y), preds, y))
  
  # create list of datasets 
  obs_dfs <- list(cmplt_cases = obs_cc, 
                  mean_imp = obs_mimp, 
                  reg_imp = obs_regimp)
  
  ### Get stats for evaluation
  return(map(obs_dfs, eval_stats))

}

## Test the function
test_out <- eval_impute(n=1000, 
                        beta_x = c(0, 0), beta_y = c(3, 1, 2), 
                        p_mis = .2)
```

```{r run simulation}
set.seed(1345)
L = 5
seeds <- sample(1:9999, size = L, replace = FALSE)

sim_out <- map(seeds, eval_impute, 
               n = 1000, beta_x = c(0, 0), beta_y = c(3, 1, 2), 
               p_mis = .2)

# reshape
sim_dfs <- map(sim_out %>% 
                transpose, transpose) %>%
  map(function(x) map(x, bind_rows))
```

```{r summarize}
sim_dfs %>%
  map(function(x) map(x, summarize_all, mean))
```


```{r test for stackoverflow}
library(purrr)

list_norms <- function(n, r, seed) {
  set.seed(seed)
  map(1:r, rnorm,n = n) %>%
    set_names(c("A", "B", "C"))
}

set.seed(1000)
mylist <- map(sample(1:1000, 5), list_norms, n = 3, r = 3)

purrr::reduce(mylist, .f = function(x) {
  rbind(x[[1]])
})

simplelist <- map(1:3, function(x) rbind(rnorm(n = 3)))

reduce(simplelist, rbind)

```


```{r}
list_norms <- function(n, r, seed) {
  set.seed(seed)
   map(1:r, rnorm, n = n) %>%
  set_names(c("A", "B", "C")) #%>%
  #as_tibble
}

list_norms(5, 3, 1)

map_dfr(1:10, list_norms, n = 5, r = 3, .id = 'grp')
```





